[package]
name = "bw-bool"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A linter and parser for Brandwatch boolean search queries"
license = "MIT"
repository = "https://github.com/your-repo/bw-bool"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
pretty_assertions = "1.0"
tempfile = "3.0"

[[bin]]
name = "bw-bool"
path = "src/main.rs"

[lib]
name = "bw_bool"
path = "src/lib.rs"