[package]
name = "bwq-lint"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A linter and parser for Brandwatch query files (.bwq)"
license = "MIT"
repository = "https://github.com/your-repo/bwq-lint"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tower-lsp = "0.20"
tokio = { version = "1", features = ["full"] }
glob = "0.3"

[dev-dependencies]
pretty_assertions = "1.0"
tempfile = "3.0"

[[bin]]
name = "bwq-lint"
path = "src/main.rs"

[lib]
name = "bwq_lint"
path = "src/lib.rs"