[package]
name = "bwq-lint"
version = "0.1.0"
edition = "2021"
authors = ["Milo Stroik <mmstroik@gmail.com>"]
description = "A linter and parser for Brandwatch query files (.bwq)"
license = "MIT"
repository = "https://github.com/mmstroik/bwq-lint"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
glob = "0.3.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
tower-lsp = "0.20.0"


[dev-dependencies]
pretty_assertions = "1.4.1"
tempfile = "3.20.0"


[[bin]]
name = "bwq-lint"
path = "src/main.rs"

[lib]
name = "bwq_lint"
path = "src/lib.rs"
