[package]
name = "bwq-lint"
version = "0.2.0"
authors = ["Milo Stroik <mmstroik@gmail.com>"]
edition = "2021"
description = "A linter and parser for Brandwatch query files (.bwq)"
repository = "https://github.com/mmstroik/bwq-lint"
license = "MIT"

[lib]
name = "bwq_lint"
path = "src/lib.rs"

[[bin]]
name = "bwq-lint"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
crossbeam-channel = "0.5.15"
glob = "0.3.2"
lsp-server = "0.7.8"
lsp-types = "0.97.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = { version = "1.45.1", features = ["full"] }

[dev-dependencies]
pretty_assertions = "1.4.1"
tempfile = "3.20.0"

